### ISSUE TITLE
issues caught by Purr Data CI

### ISSUE THREAD

**Issue by jonwwilkes** [ericlyon/pd-lyonpotpourri#1]
Hi Eric,

Here are all the issues caught by the Purr Data CI which now covers all dsp_add and perfroutines:

* inside all your dsp_add calls explicitly cast `sp[0]->s_n`-- which is of type `int`-- to `(t_int)`. Otherwise you hit undefined behavior because varargs does not automatically promote int. (Note: you can still cast to `int` inside the perfroutine when dereferencing the pointer.)
* in bashfest_new set x->wavename to `&s_` if there were no args provided. Otherwise it will crash when dsp is turned on.
* same crasher for buffet_new
* in rotapan_new check if rchans is less than 1 and if so set it to 1. Otherwise you hit a divide-by-zero exception in your dsp routine with `%` binop
* inside `magfreq_analysis~` it looks like the power_of_two routine lets zero pass and consequently causes a segfault

**Comment by ericlyon** [comment]
Thanks, Jon.

I'll propagate these back to the active github distros.

Eric

**Comment by ericlyon** [comment]
I think these are all now fixed. The poorly named function power_of_two() is a test that returns 1 if the input is a power of 2, and zero otherwise. This should not cause crashes. 

Eric
