### ISSUE TITLE
LyonPotpourri 3.0 - soon ready for release

### ISSUE THREAD

**Issue by ericlyon** [ericlyon/pd-lyonpotpourri#14]
LyonPotpourri 3.0 for Pd may soon be ready for release. All of the help files have been rewritten, and several bugs have been fixed in the process. Now the externals need to be kicked around to see if there are any crashes, errors in the help files, or other issues that would be a problem for users. @porres and @Lucarda, it would be great if you are able to take a look.

There are some longer-term issues with the code, which currently has a lot of cruft that needs to be trimmed, but that's not a concern for this release, unless it causes an issue that a user would notice. It would be great to get v3.0.0 out the door in the coming week.

**Comment by Lucarda** [comment]
Cool. 
I'll start building and testing on Windows and Linux.

**Comment by ericlyon** [comment]
Thanks, @Lucarda, for updating the help files. I further updated a few of them, mainly where I had previously forgotten the "lyonpotpourri" prefix. I'm thinking to leave a couple days to play around with the externals, and if there are no horrible problems, then onto the official v3.0.0 release.

**Comment by porres** [comment]
test binaries? :)

**Comment by ericlyon** [comment]
> test binaries? :)

That is the way.

**Comment by porres** [comment]
I'm trying to achieve a new icon patch with colors that hopefully everybody will find more aesthetically pleasent :)

**Comment by ericlyon** [comment]
> I'm trying to achieve a new icon patch with colors that hopefully everybody will find more aesthetically pleasent :)

Happy to have a look at your suggestion, though no promises that I will like it better :)

**Comment by Lucarda** [comment]
May be some space to the left must be added to the holding rectangle.

This is how it renders on Windows:


![windows](https://user-images.githubusercontent.com/25239522/111195466-0a0d4900-859b-11eb-9553-d14f579709a1.png)





and on Linux:


![linux](https://user-images.githubusercontent.com/25239522/111195501-14c7de00-859b-11eb-89b1-697de532fe51.png)

**Comment by ericlyon** [comment]
That's interesting. Looks great on Mac, so it sounds like we need extra space on both sides. Or is it a font issue?
![Screen Shot 2021-03-15 at 1 54 50 PM](https://user-images.githubusercontent.com/2522169/111198644-2b1f6b00-8596-11eb-8544-3356bc96d9ff.png)

**Comment by ericlyon** [comment]
In any case, please make a version with enough space to fit on Windows & Linux, and attach here. I'll give it a try on Mac, and if it looks good there too, I'll update in the distro. Thanks!

**Comment by Lucarda** [comment]
Yes is a font issue. Recently macOS switched to use the "Menlo" font. Windows and Linux use "DejaVuSansMono-Bold".

I'll try and push.

**Comment by porres** [comment]
> Yes is a font issue. Recently macOS switched to use the "Menlo" font. 

but that was a fix rather than something that introduced a bug. Menlo should act like DejaVu... let's take this to the pd list/github

**Comment by ericlyon** [comment]
> > Yes is a font issue. Recently macOS switched to use the "Menlo" font.
> 
> but that was a fix rather than something that introduced a bug. Menlo should act like DejaVu... let's take this to the pd list/github

Cool. Meanwhile, let's get the spacing issue fixed for our upcoming release of LyonPotpourri.

**Comment by Lucarda** [comment]
Please wait. I can no longer push. I was doing it with my password until now but since i created a token i cant push any more.
Will try a fork.

**Comment by ericlyon** [comment]
Yes, please use a PR. Thanks!

**Comment by Lucarda** [comment]
#20 look like this on Windows:

![win2](https://user-images.githubusercontent.com/25239522/111204103-8ce6d180-85a4-11eb-9f0c-bab507f537b8.png)

**Comment by ericlyon** [comment]
I can see that a few of the help files will need to be adjusted, where overlaps have been introduced with the text to the right. Would you like to take care of that, or should I?

**Comment by Lucarda** [comment]
I'll do it. :)

**Comment by Lucarda** [comment]
While working on #21 I found that granulesf~ is missing the initial description.

**Comment by ericlyon** [comment]
Please use this one: - sound file granulator

**Comment by Lucarda** [comment]
> Please use this one: - sound file granulator

done.

**Comment by ericlyon** [comment]
Looks like we're really close now. I'll create a release tag on Wednesday. If no major problems emerge by then, it will go out that day. Thanks for all of your help on this!

**Comment by Lucarda** [comment]
Ok, so no freeze and test binaries then? 
I'm Ok without them.

**Comment by ericlyon** [comment]
I'm not planning to update the code unless a nasty bug emerges.

**Comment by Lucarda** [comment]
a "nasty bug" my emerge if people can test it. :)
We might give them binaries?

**Comment by ericlyon** [comment]
That's what v3.0.1 is for :)

**Comment by Lucarda** [comment]
Ok then. We are done until Wednesday. :)

**Comment by ericlyon** [comment]
You can still try to make the objects crash until Wednesday :)

**Comment by ericlyon** [comment]
Just created the v3.0.0 tag. Please send binaries for this release. Thanks @Lucarda & @porres!

**Comment by Lucarda** [comment]
@ericlyon  the binaries are [here](https://nc.nubegris.com.ar/index.php/s/3Z8HNwnPLeN6c9N)

Do I upload to Deken or you (or @porres) do it?

**Comment by ericlyon** [comment]
> @ericlyon the binaries are [here](https://nc.nubegris.com.ar/index.php/s/3Z8HNwnPLeN6c9N)
> 
> Do I upload to Deken or you (or @porres) do it?

Please send me the binaries, and I'll put them up in the release. You guys can take care of Deken however you like. Thanks!

**Comment by Lucarda** [comment]
> Please send me the binaries, and I'll put them up in the release.

They are in the "here" link on my previous post. :)

**Comment by Lucarda** [comment]
I'll upload to Deken.

**Comment by ericlyon** [comment]
Great! I think we're sorted for v3.0.0 then.

**Comment by Lucarda** [comment]
Yes it's done!!!

Can you test geting the lib from deken?

I'm going to dinner. :)

**Comment by ericlyon** [comment]
> Yes it's done!!!
> 
> Can you test geting the lib from deken?
> 
> I'm going to dinner. :)

Yep, works from a Mac computer.

**Comment by Lucarda** [comment]
I had also checked the other OS/archs Deken packages and they are also Ok.

Pd-list announcement?

(looks that this issue can be closed)

:)

**Comment by ericlyon** [comment]
> I had also checked the other OS/archs Deken packages and they are also Ok.
> 
> Pd-list announcement?
> 

Sure - go for it!
Cheers,Eric
