### ISSUE TITLE
no clock_free called for clocks in click2bang~, click2float~, sigseq~, or splitspec~

### ISSUE THREAD

**Issue by sebshader** [ericlyon/pd-lyonpotpourri#2]
the clocks aren't freed when the objects are destroyed/freed. This can cause pd to crash with a segfault when the object is destroyed since the clock is still on the scheduling list and will reference items in the object when it calls the callback

**Comment by ericlyon** [comment]
Thanks for the report. I just updated click2bang~. Please let me know if there are any side effects. If not, I'll fix the other affected objects.

**Comment by sebshader** [comment]
@ericlyon I only found the bug with click2float~. However, I think click2bang~ looks good except that I think clock_free needs to be used instead of free, in order to free the clock (bc clock_free will call clock_unset, which is what will take it off of the scheduling list)

**Comment by ericlyon** [comment]
Updated click2bang~. The other three objects still require this fix.

**Comment by ericlyon** [comment]
All four externals updated with clock_free().

**Comment by sebshader** [comment]
@ericlyon does click2float~ still need it?

**Comment by ericlyon** [comment]
Forgot to upload the new files. Should be fine now.
