### ISSUE TITLE
array-access not 64bit safe

### ISSUE THREAD

**Issue by umlaeute** [ericlyon/pd-lyonpotpourri#4]
the `[vdp~]` object uses array-access that does not work on 64bit operating systems.

you can confirm this by sending it a `copy_to_buffer` message, which will give you a nice fat red warning (on 64bit systems).
e.g. in the help-patch:

> an operation on the array 'vdp-catch' in the patch 'capture'
> failed since it uses garray_getfloatarray while running 64-bit

@Lucarda ^^^

**Comment by Lucarda** [comment]
@umlaeute 
> an operation on the array 'vdp-catch' in the patch 'capture'
failed since it uses garray_getfloatarray while running 64-bit

confirmed on Win(amd64)

**Comment by ericlyon** [comment]
@umlaeute - would you like to update that code?

**Comment by umlaeute** [comment]
sure

**Comment by ericlyon** [comment]
Thanks!
