### ISSUE TITLE
most objects crash if they receive a [dsp( message

### ISSUE THREAD

**Issue by umlaeute** [ericlyon/pd-lyonpotpourri#5]
of the 54 signal objects in lyonpotpourri, 40 will crash whenever you send them a `[dsp(` message.

e.g.:

~~~
[dsp(
|
[adsr~]
~~~

**Comment by ericlyon** [comment]
I believe the solution is to define the dsp method as "A_CANT." Updated in adsr~ code accordingly. If this solution works, then should be propagated to all affected objects.
