### ISSUE TITLE
too generic names for library functions

### ISSUE THREAD

**Issue by umlaeute** [ericlyon/pd-lyonpotpourri#8]
the functions from the `liblyonpotpourri` helper library are *very* generic (`transpose`, `cfft`, `makehamming`,...), and are thus likely to clash with symbols from other libraries.

since the library functions cannot be made static (see also #7), you should prefix their names with something unique. `lyonpotpourri_` would be an obvious prefix.

**Comment by ericlyon** [comment]
Exposed functions now prepended with lpp_.
